name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Lint and format
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Build
        run: npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        id: e2e_tests
        run: |
          echo "status=failed" >> $GITHUB_OUTPUT
          xvfb-run npm run test:e2e
          echo "status=success" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Prepare coverage artifacts for upload
        run: |
          mkdir -p gh_page/coverage
          cp -r ./coverage/lcov-report gh_page/coverage/
          cp ./coverage/coverage-summary.json gh_page/coverage/

      - name: Prepare Playwright report artifacts for upload
        run: |
          mkdir -p gh_page/playwright-report
          cp -r ./playwright-report/* gh_page/playwright-report/

      - name: Upload GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./gh_page"

      - name: Deploy GitHub Pages
        uses: actions/deploy-pages@v1

      - name: Check E2E test result
        run: |
          if [ "${{ steps.e2e_tests.outputs.status }}" == "failed" ]; then
            exit 1
          fi

      - name: Upload extension
        uses: actions/upload-artifact@v3
        with:
          name: extension
          path: extension.zip
